version: "3.3"
services:
  dnsproxy:
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - "ARGS=-u=https://doh-tw1.blahdns.com/dns-query -u quic://dot-tw1.blahdns.com:784 -f 94.140.14.14 -b 1.1.1.1 --cache --cache-min-ttl=30 --cache-max-ttl=300 --cache-optimistic --edns "
    image: ookangzheng/dnsproxy
