services:
  dnsproxy:
    container_name: dnsproxy
    image: gsealy/dnsproxy:0.0.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    privileged: true
    sysctls:
      - "net.ipv4.ip_forward=1"
    restart: unless-stopped
    network_mode: "bridge"