version: "3.3"
services:
  dnsproxy:
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - "ARGS=-u quic://dot-tw1.blahdns.com:784 -f 94.140.14.14 -b 168.95.1.1 -b 8.8.8.8 --cache --cache-min-ttl=10 --cache-max-ttl=90 --cache-optimistic --edns "
    image: ookangzheng/dnsproxy
