version: "3.3"
services:
  dnsproxy:
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - "ARGS=-u tls://dot-tw1.blahdns.com https://doh-tw1.blahdns.com/dns-query -f 94.140.14.14 -b 1.1.1.1 -b 8.8.8.8 --cache --cache-min-ttl=10 --cache-max-ttl=90 --cache-optimistic --edns "
    image: ookangzheng/dnsproxy:arm64
    privileged: true
    sysctls:
      - "net.ipv4.ip_forward=1"
